# 1_Formatting SEO_Original_Dataset

## Objectives

The objective of this Jupyter Notebook is to address missing values and validate the consistency of each column by applying logical checks and cross-referencing within the original dataset.

### Importing dataset

In [1]:
import os
import numpy as np
import pandas as pd
import zipfile

In [2]:
# ===========================================
# 1. Import Libraries and Load the Dataset
# ===========================================

# Load the raw SEO dataset
original_seo = pd.read_csv(r"data\Original SEO ISSUES Dataset RAW\SEO ISSUES 200001 - 202312v3.0.Exclcsv.csv")

# Display dataset info: column names, non-null count, data types
original_seo.info()

# Show first 10 rows of the dataset
original_seo.head(10)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 14308 entries, 0 to 14307
Data columns (total 43 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   IPO_flag                        14308 non-null  bool
 1   original_IPO_flag               14308 non-null  bool
 2   Price_Date_Diff                 11793 non-null  float64
 3   Deal_PermID                     14308 non-null  float64
 4   BB_Deal_Number                  14308 non-null  int64
 5   Issue_Date                      14308 non-null  object
 6   Offer_Year                      14308 non-null  int64
 7   Issuer_Exchange                 13740 non-null  object
 8   New_Issues_Primary_Exchange     13738 non-null  object
 9   Issuer_Ticker                   13711 non-null  object
 10  Issuer_Name_Full                14308 non-null  object
 11  Issuer_CUSIP6                   14308 non-null  object
 12  Issuer_CUSIP8                   11984 non-null  object
 13  Issuer_CUSIP9                   11984 non-null  object
 14  New_Issues_Ticker               13721 non-null  object
 15  New_Issues_Company_ID           14272 non-null  object
 16  New_Issues_HiTech_Group         14308 non-null  object
 17  Not_For_Profit_Flag             14308 non-null  bool
 18  Issue_Type                      14308 non-null  object
 19  Regulation_Types                12539 non-null  object
 20  VC_Backed_IPO_Issue_Flag        11225 non-null  object
 21  PE_Backed_IPO_Issue_Flag        14308 non-null  bool
 22  Marketplace                     14308 non-null  object
 23  Market_Area                     14308 non-null  object
 24  Target_Market                   14308 non-null  object
 25  SIC                             14308 non-null  object
 26  Issuer_SDC_Industry             14308 non-null  object
 27  Share_Type_Offered              13812 non-null  object
 28  Security_Type_This_Mkt          14308 non-null  object
 29  Security_Type_All_Mkts          14308 non-null  object
 30  Offer_Price_USD                 14301 non-null  float64
 31  Free_Float_at_IPO               26 non-null     float64
 32  Shares_Offered_All_Mkts         14285 non-null  float64
 33  Shares_Offered_This_Mkt         14308 non-null  int64
 34  Primary_Amt_Offered_All_Mkts    12288 non-null  float64
 35  Primary_Amt_Offered_This_Mkt    12288 non-null  float64
 36  Secondary_Amt_Offered_All_Mkts  2466 non-null   float64
 37  Secondary_Amt_Offered_This_Mkt  2462 non-null   float64
 38  Price_at_Close_Issue_Date       10474 non-null  float64
 39  Price_at_Close_Offer_Date       10992 non-null  float64
 40  Price_1_Day_After               10968 non-null  float64
 41  Price_1_Day_Before              10939 non-null  float64
 42  Offer_Price_Available           14308 non-null  object
dtypes: bool(4), float64(13), int64(3), object(23)
memory usage: 4.3+ MB

,IPO_flag,original_IPO_flag,Price_Date_Diff,Deal_PermID,BB_Deal_Number,Issue_Date,Offer_Year,Issuer_Exchange,New_Issues_Primary_Exchange,Issuer_Ticker,...,Shares_Offered_This_Mkt,Primary_Amt_Offered_All_Mkts,Primary_Amt_Offered_This_Mkt,Secondary_Amt_Offered_All_Mkts,Secondary_Amt_Offered_This_Mkt,Price_at_Close_Issue_Date,Price_at_Close_Offer_Date,Price_1_Day_After,Price_1_Day_Before,Offer_Price_Available
0,False,False,NaN,1.540000e+11,2157914012,1/01/2010,2010,OTC,OTC,CCRE,...,255000,0.37,0.03,NaN,NaN,NaN,NaN,NaN,NaN,Yes
1,False,False,1.0,1.540000e+11,2143389005,3/01/2010,2010,NYSE Amex;Pink Sheet,NYSE Amex,ANX,...,19000,19.00,19.00,NaN,NaN,NaN,NaN,NaN,NaN,Yes
2,False,False,0.0,1.540000e+11,2143700002,4/01/2010,2010,Nasdaq,Nasdaq,TXCC,...,1950000,3.12,3.12,NaN,NaN,1.99,1.99,1.86,2.10,Yes
3,False,False,0.0,1.540000e+11,2143708002,4/01/2010,2010,Nasdaq,Nasdaq,CVVT,...,2414113,21.73,21.73,NaN,NaN,9.40,9.40,9.45,9.24,Yes
4,False,False,0.0,1.540000e+11,2144205002,5/01/2010,2010,New York Stock Exchange,New York Stock Exchange,TYY,...,1226995,27.85,27.85,NaN,NaN,24.13,23.87,23.94,24.13,Yes
5,False,False,0.0,1.540000e+11,2144222012,5/01/2010,2010,OTC,OTC,ORNI,...,10016250,2.50,2.50,NaN,NaN,NaN,NaN,NaN,NaN,Yes
6,False,False,0.0,1.540000e+11,2144076002,6/01/2010,2010,New York Stock Exchange,New York Stock Exchange,ETP,...,8500000,380.12,380.12,NaN,NaN,NaN,45.45,45.47,45.30,Yes
7,False,False,0.0,1.540000e+11,2113998002,6/01/2010,2010,Nasdaq,Nasdaq,COSI,...,10000000,5.00,5.00,NaN,NaN,0.66,0.70,0.71,0.66,Yes
8,False,False,0.0,1.540000e+11,2143816002,6/01/2010,2010,New York Stock Exchange,New York Stock Exchange,BZH,...,19500000,89.70,89.70,NaN,NaN,4.77,5.13,5.15,4.77,Yes
9,False,False,0.0,1.540000e+11,2144485002,6/01/2010,2010,Nasdaq,Nasdaq,ZGEN,...,14000000,84.00,84.00,NaN,NaN,6.77,6.11,6.25,6.77,Yes

In [51]:
# ===========================================
# 2. Handle Missing Values
# ===========================================

# Check total missing values per column
original_seo.isnull().sum()

# Fill missing 'Shares_Offered_All_Mkts' using values from 'Shares_Offered_This_Mkt'
original_seo['Shares_Offered_All_Mkts'] = original_seo['Shares_Offered_All_Mkts'].fillna(original_seo['Shares_Offered_This_Mkt'])

# Fill missing 'Issuer_Ticker' using 'New_Issues_Ticker'
original_seo['Issuer_Ticker'] = original_seo['Issuer_Ticker'].fillna(original_seo['New_Issues_Ticker'])

# Replace missing values in 'Price_Date_Diff' with 0
original_seo['Price_Date_Diff'] = original_seo['Price_Date_Diff'].fillna(0)

# Preview the cleaned dataset
original_seo.head()

,IPO_flag,original_IPO_flag,Price_Date_Diff,Deal_PermID,BB_Deal_Number,Issue_Date,Offer_Year,Issuer_Exchange,New_Issues_Primary_Exchange,Issuer_Ticker,...,Shares_Offered_This_Mkt,Primary_Amt_Offered_All_Mkts,Primary_Amt_Offered_This_Mkt,Secondary_Amt_Offered_All_Mkts,Secondary_Amt_Offered_This_Mkt,Price_at_Close_Issue_Date,Price_at_Close_Offer_Date,Price_1_Day_After,Price_1_Day_Before,Offer_Price_Available
0,False,False,0.0,1.540000e+11,2157914012,1/01/2010,2010,OTC,OTC,CCRE,...,255000,0.37,0.03,NaN,NaN,NaN,NaN,NaN,NaN,Yes
1,False,False,1.0,1.540000e+11,2143389005,3/01/2010,2010,NYSE Amex;Pink Sheet,NYSE Amex,ANX,...,19000,19.00,19.00,NaN,NaN,NaN,NaN,NaN,NaN,Yes
2,False,False,0.0,1.540000e+11,2143700002,4/01/2010,2010,Nasdaq,Nasdaq,TXCC,...,1950000,3.12,3.12,NaN,NaN,1.99,1.99,1.86,2.10,Yes
3,False,False,0.0,1.540000e+11,2143708002,4/01/2010,2010,Nasdaq,Nasdaq,CVVT,...,2414113,21.73,21.73,NaN,NaN,9.40,9.40,9.45,9.24,Yes
4,False,False,0.0,1.540000e+11,2144205002,5/01/2010,2010,New York Stock Exchange,New York Stock Exchange,TYY,...,1226995,27.85,27.85,NaN,NaN,24.13,23.87,23.94,24.13,Yes

In [52]:
# ===========================================
# 3. Column Validation and Cleaning
# ===========================================

# Find rows where Security_Type mismatches between the two markets
original_seo[original_seo['Security_Type_This_Mkt'] != original_seo['Security_Type_All_Mkts']]

# Decision: Drop 'Security_Type_All_Mkts' since it has fewer distinct values

,IPO_flag,original_IPO_flag,Price_Date_Diff,Deal_PermID,BB_Deal_Number,Issue_Date,Offer_Year,Issuer_Exchange,New_Issues_Primary_Exchange,Issuer_Ticker,...,Shares_Offered_This_Mkt,Primary_Amt_Offered_All_Mkts,Primary_Amt_Offered_This_Mkt,Secondary_Amt_Offered_All_Mkts,Secondary_Amt_Offered_This_Mkt,Price_at_Close_Issue_Date,Price_at_Close_Offer_Date,Price_1_Day_After,Price_1_Day_Before,Offer_Price_Available
758,False,False,0.0,1.540000e+11,2237379012,30/06/2010,2010,Nasdaq,Nasdaq,SNSS,...,43500000,26.97,11.96,NaN,NaN,NaN,NaN,NaN,NaN,Yes
761,False,False,0.0,1.540000e+11,2198199013,30/06/2010,2010,Nasdaq,Nasdaq,PBIB,...,597000,11.06,6.87,NaN,NaN,12.62,12.62,12.19,12.65,Yes
977,False,False,0.0,1.540000e+11,2213838013,19/08/2010,2010,Nasdaq,Nasdaq,STSA,...,3881700,514.36,357.12,NaN,NaN,0.65,0.64,0.64,0.65,Yes
1043,False,False,0.0,1.540000e+11,2222281013,14/09/2010,2010,OTC,OTC,CNER,...,4,15.00,2.61,NaN,NaN,NaN,NaN,NaN,NaN,Yes
1197,False,False,0.0,1.540000e+11,2231540012,14/10/2010,2010,OTC,OTC,CYRX,...,832868,4.26,0.64,NaN,NaN,0.77,0.77,0.79,0.74,Yes
1453,False,False,0.0,1.540000e+11,2375114002,6/12/2010,2010,Frankfurt;OTC,OTC,SLGLF,...,100000000,0.31,0.21,NaN,NaN,NaN,0.00,0.01,0.00,Invalid
2724,False,False,0.0,1.540000e+11,2345188002,5/10/2011,2011,BMFBOVESPA;New York Stock Exchange,BMFBOVESPA,TIMP3,...,6812056,891.41,155.31,NaN,NaN,NaN,0.00,0.00,0.00,Yes
3949,False,False,0.0,1.540000e+11,2467923013,14/11/2012,2012,Pink Sheet,Pink Sheet,CFIS,...,56708,19.68,5.67,NaN,NaN,NaN,NaN,NaN,NaN,Yes
3951,False,False,0.0,1.540000e+11,2467922013,14/11/2012,2012,Pink Sheet,Pink Sheet,CFIS,...,133411,19.68,13.34,NaN,NaN,NaN,NaN,NaN,NaN,Yes
4187,False,False,0.0,1.540000e+11,2494298013,4/02/2013,2013,OTC,OTC,PSMH,...,2000,5.70,2.00,NaN,NaN,NaN,NaN,NaN,NaN,Yes
4350,False,False,0.0,1.540000e+11,2507705002,19/03/2013,2013,Nasdaq,Nasdaq,CBMX,...,1610,2.01,1.61,NaN,NaN,NaN,3.20,3.08,3.40,Yes
4369,False,False,0.0,1.540000e+11,2499906002,21/03/2013,2013,Santiago;New York Stock Exchange,New York Stock Exchange,ENI,...,33508834,2378.79,616.56,NaN,NaN,NaN,NaN,NaN,NaN,Yes
4689,False,False,0.0,1.540000e+11,2522218002,9/07/2013,2013,Mexico;Nasdaq,Nasdaq,OMAB,...,4500000,NaN,NaN,185.80,111.4,NaN,NaN,NaN,NaN,Yes
4890,False,False,0.0,1.540000e+11,2524987002,12/09/2013,2013,New York Stock Exchange;Santiago,Santiago,CCU,...,4290921,663.19,111.56,NaN,NaN,NaN,26.40,26.59,26.68,Yes
5590,False,False,0.0,1.540000e+11,2625834013,3/04/2014,2014,OTC,OTC,PSMH,...,1400,3.20,1.40,NaN,NaN,NaN,NaN,NaN,NaN,Yes
5626,False,False,0.0,1.540000e+11,2629542002,17/04/2014,2014,NYSE MKT;Australia;OTC,Australia,SSN,...,11255541,1.43,0.21,NaN,NaN,0.37,0.37,0.38,0.46,Yes
5645,False,False,0.0,1.540000e+11,2632997002,28/04/2014,2014,New York Stock Exchange;BMFBOVESPA;BMFBOVESPA;...,BMFBOVESPA,OIBR3,...,396589982,5939.89,384.69,NaN,NaN,2.25,0.93,0.99,2.25,Yes
5648,False,False,0.0,1.540000e+11,2632998002,28/04/2014,2014,New York Stock Exchange;BMFBOVESPA;BMFBOVESPA;...,BMFBOVESPA,OIBR3,...,828881795,5939.89,741.02,NaN,NaN,NaN,0.00,0.00,0.00,Yes
7192,False,False,0.0,1.540000e+11,2918430002,3/12/2015,2015,Nasdaq,Nasdaq,ANCI,...,750,7.50,0.75,NaN,NaN,0.92,0.92,0.64,0.77,Yes
8604,False,False,0.0,1.540000e+11,3102335002,8/05/2017,2017,Nasdaq,Nasdaq,MLCO,...,81995799,1163.13,576.92,NaN,NaN,NaN,NaN,NaN,NaN,Yes
8644,False,False,0.0,1.540000e+11,3109260002,23/05/2017,2017,Nasdaq,Nasdaq,EVLV,...,228705,5.50,0.26,NaN,NaN,NaN,NaN,NaN,NaN,Yes
8778,False,False,0.0,1.540000e+11,3129234002,18/07/2017,2017,New York Stock Exchange,NaN,BFR,...,21737310,348.69,344.54,NaN,NaN,NaN,NaN,NaN,NaN,Yes
10180,False,False,0.0,1.540000e+11,3377783002,5/04/2019,2019,Nasdaq,Nasdaq,SYRS,...,8667333,70.00,65.00,NaN,NaN,7.48,7.40,6.82,7.48,Yes
10487,False,False,0.0,1.540000e+11,3451449002,11/09/2019,2019,Euro Paris;Euronext B;Nasdaq,Euronext B,CYAD,...,1717391,20.00,17.17,NaN,NaN,NaN,0.00,0.00,0.00,Yes
11597,False,False,0.0,1.540000e+11,3637591002,1/10/2020,2020,BMFBOVESPA;BMFBOVESPA;OTC,BMFBOVESPA,SUZB3,...,13180000,107.42,107.42,1116.95,NaN,8.19,8.14,8.46,8.19,Yes
13051,False,False,0.0,1.540000e+11,3926756002,9/06/2022,2022,BMFBOVESPA;BMFBOVESPA;BMFBOVESPA,BMFBOVESPA,ELET3,...,9783100,5075.77,84.43,895.60,NaN,NaN,NaN,NaN,NaN,Yes
13825,False,False,0.0,1.540000e+11,4087342002,22/06/2023,2023,New York Stock Exchange,New York Stock Exchange,LCID,...,265693703,3000.00,1814.69,NaN,NaN,5.73,5.47,5.55,5.73,Yes
13871,False,False,0.0,1.540000e+11,4117151002,12/07/2023,2023,Nasdaq,Nasdaq,BCYC,...,4705882,200.00,100.00,NaN,NaN,NaN,NaN,NaN,NaN,Yes
13967,False,False,0.0,1.540000e+11,4118273002,8/08/2023,2023,Nasdaq,Nasdaq,MRTX,...,1121736,300.00,31.18,NaN,NaN,NaN,NaN,NaN,NaN,Yes
13998,False,False,0.0,1.540000e+11,4122053002,18/08/2023,2023,New York Stock Exchange,New York Stock Exchange,CVNA,...,2720795,283.50,126.00,NaN,NaN,NaN,NaN,NaN,NaN,Yes
14093,False,False,0.0,1.540000e+11,4139570002,28/09/2023,2023,Nasdaq,Nasdaq,MDGL,...,2048098,500.00,310.68,NaN,NaN,NaN,NaN,NaN,NaN,Yes
14116,False,False,0.0,1.540000e+11,4144513002,11/10/2023,2023,Nasdaq,Nasdaq,ATXS,...,1571093,64.00,10.23,NaN,NaN,NaN,NaN,NaN,NaN,Yes

In [53]:
# ===========================================
# 4. Clean Invalid 'Offer_Price_Available' Values
# ===========================================

# Define a list of invalid indicators
invalid_vals = ['invalid', 'n/a', 'na', 'no']

# Replace 'Offer_Price_USD' with NaN if the corresponding 'Offer_Price_Available' is invalid
original_seo.loc[
    original_seo['Offer_Price_Available'].str.lower().isin(invalid_vals),
    'Offer_Price_USD'
] = np.nan

# Standardize invalid values in 'Offer_Price_Available' column as "missing"
original_seo['Offer_Price_Available'] = original_seo['Offer_Price_Available'].apply(
    lambda x: 'missing' if str(x).strip().lower() in invalid_vals else x
)

In [54]:
# ===========================================
# 5. Drop Unnecessary Columns
# ===========================================
original_seo.drop(columns=[
    "Free_Float_at_IPO", "Secondary_Amt_Offered_All_Mkts", "Secondary_Amt_Offered_This_Mkt",
    "Offer_Price_Available", "IPO_flag", "original_IPO_flag", "BB_Deal_Number",
    "Not_For_Profit_Flag", "PE_Backed_IPO_Issue_Flag", "Target_Market",
    "Security_Type_All_Mkts", "Deal_PermID"
], inplace=True)

# Confirm column drops
original_seo.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 14308 entries, 0 to 14307
Data columns (total 31 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   Price_Date_Diff               14308 non-null  float64
 1   Issue_Date                    14308 non-null  object
 2   Offer_Year                    14308 non-null  int64
 3   Issuer_Exchange               13740 non-null  object
 4   New_Issues_Primary_Exchange   13738 non-null  object
 5   Issuer_Ticker                 13721 non-null  object
 6   Issuer_Name_Full              14308 non-null  object
 7   Issuer_CUSIP6                 14308 non-null  object
 8   Issuer_CUSIP8                 11984 non-null  object
 9   Issuer_CUSIP9                 11984 non-null  object
 10  New_Issues_Ticker             13721 non-null  object
 11  New_Issues_Company_ID         14272 non-null  object
 12  New_Issues_HiTech_Group       14308 non-null  object
 13  Issue_Type                    14308 non-null  object
 14  Regulation_Types              12539 non-null  object
 15  VC_Backed_IPO_Issue_Flag      11225 non-null  object
 16  Marketplace                   14308 non-null  object
 17  Market_Area                   14308 non-null  object
 18  SIC                           14308 non-null  object
 19  Issuer_SDC_Industry           14308 non-null  object
 20  Share_Type_Offered            13812 non-null  object
 21  Security_Type_This_Mkt        14308 non-null  object
 22  Offer_Price_USD               14248 non-null  float64
 23  Shares_Offered_All_Mkts       14308 non-null  float64
 24  Shares_Offered_This_Mkt       14308 non-null  int64
 25  Primary_Amt_Offered_All_Mkts  12288 non-null  float64
 26  Primary_Amt_Offered_This_Mkt  12288 non-null  float64
 27  Price_at_Close_Issue_Date     10474 non-null  float64
 28  Price_at_Close_Offer_Date     10992 non-null  float64
 29  Price_1_Day_After             10968 non-null  float64
 30  Price_1_Day_Before            10939 non-null  float64
dtypes: float64(9), int64(2), object(20)
memory usage: 3.4+ MB

In [55]:
# ===========================================
# 6. Check for Ticker Mismatches
# ===========================================
# Compare cleaned 'Issuer_Ticker' with 'New_Issues_Ticker' (case insensitive)
mismatched_rows = original_seo[
    original_seo['Issuer_Ticker'].str.strip().str.upper() != original_seo['New_Issues_Ticker'].str.strip().str.upper()
]

# Preview mismatches
mismatched_rows.head(5)

,Price_Date_Diff,Issue_Date,Offer_Year,Issuer_Exchange,New_Issues_Primary_Exchange,Issuer_Ticker,Issuer_Name_Full,Issuer_CUSIP6,Issuer_CUSIP8,Issuer_CUSIP9,...,Security_Type_This_Mkt,Offer_Price_USD,Shares_Offered_All_Mkts,Shares_Offered_This_Mkt,Primary_Amt_Offered_All_Mkts,Primary_Amt_Offered_This_Mkt,Price_at_Close_Issue_Date,Price_at_Close_Offer_Date,Price_1_Day_After,Price_1_Day_Before
1,1.0,3/01/2010,2010,NYSE Amex;Pink Sheet,NYSE Amex,ANX,ADVENTRX Pharmaceuticals Inc,00764X,00764X10,00764X103,...,Units,1000.00,19000.0,19000,19.00,19.00,NaN,NaN,NaN,NaN
11,0.0,6/01/2010,2010,OTC;Pink Sheet,OTC,MDXG,MiMedX Group Inc,602496,60249610,602496101,...,Common Stock,0.60,8333333.0,8333333,5.00,5.00,NaN,NaN,NaN,NaN
18,0.0,7/01/2010,2010,Toronto Stock Exchange;NYSE Amex,Toronto Stock Exchange,AUM,Golden Minerals Co,381119,38111910,381119106,...,Common Stock,6.82,844694.0,844694,5.76,5.76,12.5,12.5,12.90,11.95
20,0.0,8/01/2010,2010,Nasdaq;Toronto Stock Exchange,Toronto Stock Exchange,TLB,OccuLogix Inc,67461T,87819310,878193101,...,Common Stock,0.93,3244766.0,1886291,3.00,1.74,1.2,1.2,1.15,1.20
29,0.0,11/01/2010,2010,Mexico;Pink Sheet,Mexico,FINDEP,Financiera Independencia SAB de CV SOFOM ENR,31770B,NaN,NaN,...,Common Stock,NaN,0.0,0,NaN,NaN,NaN,NaN,NaN,NaN

In [56]:
# ===========================================
# 7. Export Unique CUSIPs to Text File
# ===========================================

# Define folder and filename for output
output_text = r'txt files'
text_file = 'unique_issuer_cusip9.txt'
output_full_path = os.path.join(output_text, text_file)

# Save unique CUSIP9 values (after stripping and type conversion) to .txt file
original_seo['Issuer_CUSIP9'].dropna().astype(str).str.strip().unique().tofile(
    output_full_path, sep='\n', format='%s'
)

## Note for Excluding some companies
Ticker Records
Companies like Sharpspring LLC, Apollo Endosurgery Us Inc, Tellurian Inc., dELiA*s Corp, Boardwalk Pipeline Partners LP, Valeritas Holdings LLC, Daseke Inc, Forest City Enterprises Inc, Navistar International Corp, Gramercy Property Trust Inc,     were acquired by other companies and therefore they were omitted from the dataset due to no records.

Companies like Kips Bay Medical Inc, Melinta Therapeutics Inc, Adeptus Health Inc, Gryphon Gold Corp  were dissolved due to insolvency.

Companies like Burger King Worldwide Inc, AntriaBio Inc went into mergers and therefore their tickers were retired.

Companies like Amwest Imaging Inc, Helomics Corp, Global Eagle Entertainment Inc, Media General, Royal Hawaiian Orchards LP,   were delisted and ticker was retired.

Data cannot be retrieved "Acer Therapeutics Inc", 3AM Technologies Inc - Shell Company, Interdom Corp - no such company, Rainbow Coral Corp - no such company found, Dragon Beverage Inc - no such company found, Ontario Solar Energy Corp - privately held, Top Gear Inc - not found, Impact Explorations Inc - not found, Warwick Royalty & Mineral Fund III - private company, Project Augustus - no such company found, Ocean Link Fund II - not found

In Conclusion, we considered to eliminate the rows with missing Issue tickers as they were either acquired or dissolved or cannot be found due to data being private.

In [57]:
# ===========================================
# 8. Map Missing Issuer_Ticker from Issuer_Name_Full
# ===========================================

# Define a manual mapping of known company names to their correct tickers
name_to_ticker = {
    'Oncternal Therapeutics Inc': 'ONCT',
    'PDS Operating Corp': 'PDSB', # Actual Name - PDS Biotechnology Corporation
    'Summit Midstream Partners LP': 'SMC',
    'Avantor Inc': 'AVTR',
    'Gabellli Global Utility &  Income Trust': 'GLU',
    'ConnectOne Bancorp Inc': 'CNOB',
    'Achieve Life Science Inc': 'ACHV',
    'Madrigal Pharmaceuticals Inc': 'MDGL',
    'Evofem Biosciences Inc': 'EVFM',
    'Global Ship Lease Inc': 'GSL',
    'Burger King Worldwide Inc': 'QSR', # New Name - Restaurant Brands International Inc. 
    'Warby Parker Inc': 'WRBY',
    'Blue Star Foods Corp': 'BSFC',
    'Vistagen Therapeutics Inc': 'VTGN',
    'Performance Food Group Co': 'PFGC',
    'Synlogic Inc': 'SYBX',
    'Avid Bioservices Inc': 'CDMO',
    'Rocket Pharmaceuticals Ltd': 'RCKT',
    'Nabriva Therapeutics AG': 'NBRVF',
    'CHF Solutions Inc': 'NUWE', # New Name - Nuwellis, Inc.
    'Zomedica Pharmaceuticals Inc': 'ZOMDF',
    'Bancorp Inc,Wilmington, Delaware': 'TBBK', # Actual Name - The Bancorp, Inc.
    'nCino Inc': 'NCNO',
    'NeoGenomics Inc': 'NEO',
    'Edesa Biotech Inc': 'EDSA',
    'Heartland Bancorp Inc-Branch': 'HLAN', # Actual Name - Heartland BancCorp
    'Molecular Templates Inc': 'MTEMQ',
    'Pulmatrix Operating Co Inc': 'PULM', # Actual Name - Pulmatrix, Inc.
    'Golden Ocean Group Ltd': 'GOGL',
    'Wejo Group Ltd': 'WEJOF',
    'Nabriva Therapeutics AG': 'NBRVF', # New Name - Nabriva Therapeutics plc
    'Magnachip Semiconductor Sa': 'MX', # Market Name - Magnachip Semiconductor Corporation
    'Nano Labs Ltd': 'NA',
    'Freyr Battery SA': 'TE', # New Name - T1 Energy Inc.
    'ZyVersa Therapeutics Inc': 'ZVSA',
    'Atlis Motor Vehicles Inc': 'NXUR', # New Name - Nxu, Inc. (Atlis Motor is subsidiary of this company)
    'Bank of Southern California NA ,San Diego,California': 'BCAL', # New Name - California BanCorp.
    'Nuveen Preferred & Income 2022 Term Fund': 'JPC',
    'Venus Concept Canada Corp': 'VERO', # New Name  - Venus Concept Inc.
    'Sterling Bancorp': 'SBT',
    'VBI Vaccines Inc': 'VBIVQ',
    'Aurum Resources Corp': 'ASX:AUE',
    'Ottawa Bancorp Inc': 'OTTW',
    'Leo Motors Inc': 'LEOM',
    'Jupiter Gold Corp': 'JUPGF'}

# Fill missing Issuer_Ticker using the name-to-ticker mapping
original_seo['Issuer_Ticker'] = original_seo.apply(
    lambda row: name_to_ticker.get(row['Issuer_Name_Full'], row['Issuer_Ticker']) 
    if pd.isna(row['Issuer_Ticker']) else row['Issuer_Ticker'],
    axis=1
)

original_seo.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 14308 entries, 0 to 14307
Data columns (total 31 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   Price_Date_Diff               14308 non-null  float64
 1   Issue_Date                    14308 non-null  object
 2   Offer_Year                    14308 non-null  int64
 3   Issuer_Exchange               13740 non-null  object
 4   New_Issues_Primary_Exchange   13738 non-null  object
 5   Issuer_Ticker                 13794 non-null  object
 6   Issuer_Name_Full              14308 non-null  object
 7   Issuer_CUSIP6                 14308 non-null  object
 8   Issuer_CUSIP8                 11984 non-null  object
 9   Issuer_CUSIP9                 11984 non-null  object
 10  New_Issues_Ticker             13721 non-null  object
 11  New_Issues_Company_ID         14272 non-null  object
 12  New_Issues_HiTech_Group       14308 non-null  object
 13  Issue_Type                    14308 non-null  object
 14  Regulation_Types              12539 non-null  object
 15  VC_Backed_IPO_Issue_Flag      11225 non-null  object
 16  Marketplace                   14308 non-null  object
 17  Market_Area                   14308 non-null  object
 18  SIC                           14308 non-null  object
 19  Issuer_SDC_Industry           14308 non-null  object
 20  Share_Type_Offered            13812 non-null  object
 21  Security_Type_This_Mkt        14308 non-null  object
 22  Offer_Price_USD               14248 non-null  float64
 23  Shares_Offered_All_Mkts       14308 non-null  float64
 24  Shares_Offered_This_Mkt       14308 non-null  int64
 25  Primary_Amt_Offered_All_Mkts  12288 non-null  float64
 26  Primary_Amt_Offered_This_Mkt  12288 non-null  float64
 27  Price_at_Close_Issue_Date     10474 non-null  float64
 28  Price_at_Close_Offer_Date     10992 non-null  float64
 29  Price_1_Day_After             10968 non-null  float64
 30  Price_1_Day_Before            10939 non-null  float64
dtypes: float64(9), int64(2), object(20)
memory usage: 3.4+ MB

In [58]:
# ===========================================
# 9. Load External CUSIP9-Ticker Mapping File
# ===========================================

# Load zipped file containing CUSIP9-to-ticker mappings
file_path = r'data\Updated SEO ISSUES Dataset\Wharton Datasets\cusip9_ticker_data.zip'

with zipfile.ZipFile(file_path) as z:
    with z.open('dtljsdzeletkaqco.csv') as f:
        cusip9_ticker = pd.read_csv(f)

# Keep only unique cusip-ticker pairs
unique_cusip9_rows = cusip9_ticker[['cusip', 'tic']].drop_duplicates(subset=['cusip'])

In [59]:
# ===========================================
# 10. Merge CUSIP9-Ticker Data with Main Dataset
# ===========================================

# Merge external CUSIP data to the main dataset on 'Issuer_CUSIP9'
merged_df = pd.merge(unique_cusip9_rows, original_seo, 
                     how='right', left_on='cusip', right_on='Issuer_CUSIP9')

# Fill missing ticker values using previously cleaned Issuer_Ticker
merged_df['tic'] = merged_df['tic'].fillna(merged_df['Issuer_Ticker'])

In [60]:
# ===========================================
# 11. Drop and Rename Columns
# ===========================================

# Drop redundant and low-value columns
original_seo = merged_df.drop(columns=[
    "cusip", "Issuer_Ticker", "SIC", "New_Issues_Company_ID",
    "Issuer_CUSIP6", "New_Issues_Ticker", "Issuer_Exchange"
])

# Rename the merged 'tic' column to 'Issuer_Ticker'
original_seo.rename(columns={'tic': 'Issuer_Ticker'}, inplace=True)

# Drop rows where Issuer_Ticker is still missing (~3% rows)
original_seo = original_seo.dropna(subset=['Issuer_Ticker']).reset_index(drop=True)

In [61]:
# ===========================================
# 12. Set Correct Data Types
# ===========================================

# Convert numeric and date fields
original_seo['Price_Date_Diff'] = original_seo['Price_Date_Diff'].astype('int64')
original_seo['Issue_Date'] = pd.to_datetime(original_seo['Issue_Date'], format='%d/%m/%Y')

# Convert categorical fields
categorical_cols = [
    'New_Issues_Primary_Exchange', 'Issue_Type', 'VC_Backed_IPO_Issue_Flag',
    'Marketplace', 'Market_Area', 'Issuer_SDC_Industry', 'Security_Type_This_Mkt'
]
for col in categorical_cols:
    original_seo[col] = original_seo[col].astype('category')

original_seo.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 13801 entries, 0 to 13800
Data columns (total 26 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   Issuer_Ticker                 13801 non-null  object
 1   Price_Date_Diff               13801 non-null  int64
 2   Issue_Date                    13801 non-null  datetime64[ns]
 3   Offer_Year                    13801 non-null  int64
 4   New_Issues_Primary_Exchange   13724 non-null  category
 5   Issuer_Name_Full              13801 non-null  object
 6   Issuer_CUSIP8                 11943 non-null  object
 7   Issuer_CUSIP9                 11943 non-null  object
 8   New_Issues_HiTech_Group       13801 non-null  object
 9   Issue_Type                    13801 non-null  category
 10  Regulation_Types              12456 non-null  object
 11  VC_Backed_IPO_Issue_Flag      11183 non-null  category
 12  Marketplace                   13801 non-null  category
 13  Market_Area                   13801 non-null  category
 14  Issuer_SDC_Industry           13801 non-null  category
 15  Share_Type_Offered            13316 non-null  object
 16  Security_Type_This_Mkt        13801 non-null  category
 17  Offer_Price_USD               13755 non-null  float64
 18  Shares_Offered_All_Mkts       13801 non-null  float64
 19  Shares_Offered_This_Mkt       13801 non-null  int64
 20  Primary_Amt_Offered_All_Mkts  11808 non-null  float64
 21  Primary_Amt_Offered_This_Mkt  11808 non-null  float64
 22  Price_at_Close_Issue_Date     10460 non-null  float64
 23  Price_at_Close_Offer_Date     10958 non-null  float64
 24  Price_1_Day_After             10934 non-null  float64
 25  Price_1_Day_Before            10905 non-null  float64
dtypes: category(7), datetime64[ns](1), float64(8), int64(3), object(7)
memory usage: 2.1+ MB

In [62]:
# ===========================================
# 13. Load External Security Ticker Data
# ===========================================

file_path = r'data\Updated SEO ISSUES Dataset\Wharton Datasets\security_data_using_issue_ticker.zip'

with zipfile.ZipFile(file_path) as z:
    with z.open('meabriv7ju9f5juy.csv') as f:
        ext_security_ticker = pd.read_csv(f)

# Drop duplicate tickers to avoid multiple matches
ext_security_ticker = ext_security_ticker.drop_duplicates(subset='tic')

C:\Users\sjen591\AppData\Local\Temp\ipykernel_20936\4064536689.py:9: DtypeWarning: Columns (5,15) have mixed types. Specify dtype option on import or set low_memory=False.
  ext_security_ticker = pd.read_csv(f)

In [63]:
# ===========================================
# 14. Merge Additional CUSIP Info from Security File
# ===========================================

# Merge external cusip info from ticker dataset
original_seo = pd.merge(
    original_seo,
    ext_security_ticker[['tic', 'cusip']],
    how='left',
    left_on='Issuer_Ticker',
    right_on='tic'
)

# Fill missing CUSIP9 using values from external data
original_seo['Issuer_CUSIP9'] = original_seo['Issuer_CUSIP9'].fillna(original_seo['cusip'])

# Clean up helper columns
original_seo.drop(columns=['tic', 'cusip'], inplace=True)
original_seo.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 13801 entries, 0 to 13800
Data columns (total 26 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   Issuer_Ticker                 13801 non-null  object
 1   Price_Date_Diff               13801 non-null  int64
 2   Issue_Date                    13801 non-null  datetime64[ns]
 3   Offer_Year                    13801 non-null  int64
 4   New_Issues_Primary_Exchange   13724 non-null  category
 5   Issuer_Name_Full              13801 non-null  object
 6   Issuer_CUSIP8                 11943 non-null  object
 7   Issuer_CUSIP9                 13105 non-null  object
 8   New_Issues_HiTech_Group       13801 non-null  object
 9   Issue_Type                    13801 non-null  category
 10  Regulation_Types              12456 non-null  object
 11  VC_Backed_IPO_Issue_Flag      11183 non-null  category
 12  Marketplace                   13801 non-null  category
 13  Market_Area                   13801 non-null  category
 14  Issuer_SDC_Industry           13801 non-null  category
 15  Share_Type_Offered            13316 non-null  object
 16  Security_Type_This_Mkt        13801 non-null  category
 17  Offer_Price_USD               13755 non-null  float64
 18  Shares_Offered_All_Mkts       13801 non-null  float64
 19  Shares_Offered_This_Mkt       13801 non-null  int64
 20  Primary_Amt_Offered_All_Mkts  11808 non-null  float64
 21  Primary_Amt_Offered_This_Mkt  11808 non-null  float64
 22  Price_at_Close_Issue_Date     10460 non-null  float64
 23  Price_at_Close_Offer_Date     10958 non-null  float64
 24  Price_1_Day_After             10934 non-null  float64
 25  Price_1_Day_Before            10905 non-null  float64
dtypes: category(7), datetime64[ns](1), float64(8), int64(3), object(7)
memory usage: 2.1+ MB

In [64]:
# ===========================================
# 15. Final Clean-up and Export
# ===========================================

# Enforce proper dtypes again
original_seo['Price_Date_Diff'] = original_seo['Price_Date_Diff'].astype('int64')
original_seo['Issue_Date'] = pd.to_datetime(original_seo['Issue_Date'], format='%d/%m/%Y')
#original_seo['Offer_Year'] = pd.to_datetime(original_seo['Offer_Year'], errors='coerce')
original_seo['New_Issues_Primary_Exchange'] = original_seo['New_Issues_Primary_Exchange'].astype('category')
original_seo['Issue_Type'] = original_seo['Issue_Type'].astype('category')
original_seo['VC_Backed_IPO_Issue_Flag'] = original_seo['VC_Backed_IPO_Issue_Flag'].astype('category')
original_seo['Marketplace'] = original_seo['Marketplace'].astype('category')
original_seo['Market_Area'] = original_seo['Market_Area'].astype('category')
original_seo['Issuer_SDC_Industry'] = original_seo['Issuer_SDC_Industry'].astype('category')
original_seo['Security_Type_This_Mkt'] = original_seo['Security_Type_This_Mkt'].astype('category')
original_seo.info()
original_seo['Issuer_CUSIP9'] = original_seo['Issuer_CUSIP9'].astype(str)
original_seo.reset_index(drop=True, inplace=True)

# Convert CUSIP9 to string and reset index
original_seo['Issuer_CUSIP9'] = original_seo['Issuer_CUSIP9'].astype(str)
original_seo.reset_index(drop=True, inplace=True)

# Export final dataset as CSV and Parquet
output_path = r'data\Original SEO ISSUES Dataset RAW'
csv_filename = r'SEO_ISSUES_Formatted.csv'
parquet_filename = r'SEO_ISSUES_Formatted.parquet'

original_seo.to_csv(os.path.join(output_path, csv_filename), index=False)
original_seo.to_parquet(os.path.join(output_path, parquet_filename), index=False)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 13801 entries, 0 to 13800
Data columns (total 26 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   Issuer_Ticker                 13801 non-null  object
 1   Price_Date_Diff               13801 non-null  int64
 2   Issue_Date                    13801 non-null  datetime64[ns]
 3   Offer_Year                    13801 non-null  int64
 4   New_Issues_Primary_Exchange   13724 non-null  category
 5   Issuer_Name_Full              13801 non-null  object
 6   Issuer_CUSIP8                 11943 non-null  object
 7   Issuer_CUSIP9                 13105 non-null  object
 8   New_Issues_HiTech_Group       13801 non-null  object
 9   Issue_Type                    13801 non-null  category
 10  Regulation_Types              12456 non-null  object
 11  VC_Backed_IPO_Issue_Flag      11183 non-null  category
 12  Marketplace                   13801 non-null  category
 13  Market_Area                   13801 non-null  category
 14  Issuer_SDC_Industry           13801 non-null  category
 15  Share_Type_Offered            13316 non-null  object
 16  Security_Type_This_Mkt        13801 non-null  category
 17  Offer_Price_USD               13755 non-null  float64
 18  Shares_Offered_All_Mkts       13801 non-null  float64
 19  Shares_Offered_This_Mkt       13801 non-null  int64
 20  Primary_Amt_Offered_All_Mkts  11808 non-null  float64
 21  Primary_Amt_Offered_This_Mkt  11808 non-null  float64
 22  Price_at_Close_Issue_Date     10460 non-null  float64
 23  Price_at_Close_Offer_Date     10958 non-null  float64
 24  Price_1_Day_After             10934 non-null  float64
 25  Price_1_Day_Before            10905 non-null  float64
dtypes: category(7), datetime64[ns](1), float64(8), int64(3), object(7)
memory usage: 2.1+ MB

# END